services:
    task-manager:
        container_name: task-manager
        image: taskmanager.apigateway
        build:
            context: ../src/TaskManager
            dockerfile: TaskManager.ApiGateway/Dockerfile
            network: host
        network_mode: host
        environment:
          - ASPNETCORE_HTTP_PORTS=3000
          - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
          - TelegramBot__AuthToken=${TELEGRAM_BOT_TOKEN}
          - SpeechProcessingConfig__APIURI=${SPEECH_PROCESSING_SERVICE_URI}
          - ASPNETCORE_ENVIRONMENT=Release
          - JwtSettings__Secret=${JWT_SECRET}
          - YandexOAuth__RedirectUri=${OAUTH_REDIRECT_URI}
          - YandexOAuth__ClientId=${YANDEX_CLIENT_ID}
          - YandexOAuth__ClientSecret=${YANDEX_CLIENT_SECRET}
          - SwaggerPrefix=${SWAGGER_PREFIX}
          - Smtp__Username=${SMTP_USERNAME}
          - Smtp__Password=${SMTP_PASSWORD}
          - Smtp__From=${SMTP_FROM}
          - Frontend_Url=${FRONTEND_URL}
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
          interval: 30s
          timeout: 10s
          retries: 3
        depends_on:
          postgres:
            condition: service_healthy
    postgres:
        container_name: task-manager-db
        image: postgres:17
        ports:
          - "127.0.0.1:5432:5432"
        environment:
          POSTGRES_DB: tasks
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
          - backend-network
    frontend:
        container_name: task-manager-frontend
        build:
          context: ../src/frontend/voice-task
          dockerfile: Dockerfile
          network: host
        extra_hosts:
          - "host.docker.internal:host-gateway"
        ports:
          - '3005:80'
        depends_on:
          - task-manager
        networks:
          - backend-network



networks:
  backend-network:
    driver: bridge